/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/paper_plane.glb
Author: PRINCE.JACK (https://sketchfab.com/J.A.C.K)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/paper-plane-3497256a0b5a4592a88ab081ceb551ba
Title: Paper Plane
*/

import React, { forwardRef, useRef, useImperativeHandle } from "react"
import { useGLTF } from "@react-three/drei"
import { Group } from "three"

export const Model = forwardRef<Group, JSX.IntrinsicElements["group"]>(
	(props, ref) => {
		const groupRef = useRef<Group>(null)
		const { nodes, materials } = useGLTF("/paper_plane.glb") as any

		useImperativeHandle(ref, () => groupRef.current as Group, [])

		return (
			<group ref={groupRef} {...props} dispose={null}>
				{/* Apply corrective rotation here to align model's front with +Z */}
				<group scale={0.01} rotation={[0, Math.PI / 2, 0]}>
					<mesh
						geometry={nodes.Paper_Plane_Origami_GEO_LIght_MAT_0.geometry}
						material={materials.LIght_MAT}
						scale={2.104}
					/>
				</group>
			</group>
		)
	}
)

useGLTF.preload("/paper_plane.glb")
